### ISSUE TITLE
Support for Clustering

### ISSUE THREAD

**Issue by calz10** [dev-event/react-native-maps-draw#1]
hi @dev-event , 
great job btw is it possible to include clustering inside of this map package? have tried to modify it by forking and i got some typescript issue 🙏🏻 thank you.

**Comment by dev-event** [comment]
Hi) @calz10  
This is an example of how to draw on a map. You can add clustering, I wonder how exactly it should work?

**Comment by calz10** [comment]
@dev-event hi, 👍 , thank you i was able to add clustering by forking and made it as a customed component and modified a little bit. https://www.npmjs.com/package/react-native-map-clustering have added this one so it will automatically add the cluster. 😂 its just when modifying the dependency and replaces `react-native-maps` to `react-native-map-clustering` needs an initialRegion.

**Comment by calz10** [comment]
i think i could close this issue now thank you again.

**Comment by dev-event** [comment]
@calz10 nice =)
