### ISSUE TITLE
Fix: GestureHandler for Android.

### ISSUE THREAD

**Issue by iamsydali** [dev-event/react-native-maps-draw#13]
**Issue:** Unable to draw on Android
**Solution:**  Add `zIndex: 1` to GestureHandler styles in gesture-responder.tsx

**Comment by stoicrounin** [comment]
Issue still persist

> **Issue:** Unable to draw on Android **Solution:** Add `zIndex: 1` to GestureHandler styles in gesture-responder.tsx

Just confirmed that this is the solution.
This issue still exists on the project, and should get more attention!

**Comment by dev-event** [comment]
approve

чт, 12 янв. 2023 г. в 13:07, stoicrounin ***@***.***>:

**Comment by dev-event** [comment]
thanks👍

чт, 12 янв. 2023 г. в 17:18, Алексей Петрусевич ***@***.***>:
