### ISSUE TITLE
main module field that could not be resolved

### ISSUE THREAD

**Issue by minuitagency** [dev-event/react-native-maps-draw#5]
Hi, 

I seem to encounter some issue when trying to install your package: 

![image](https://user-images.githubusercontent.com/38316888/143070395-08b224dd-7d87-459f-811f-63e5a7cbec23.png)

Thank you for the great work, you're saving our project with this, 

Thanks, 

Théo

**Comment by minuitagency** [comment]
my bad, wrong package

**Comment by dev-event** [comment]
Good afternoon. This project was thought of as an example. I made it
because a lot of people needed it. Please create issues git

[image: image.png]


вт, 23 нояб. 2021 г. в 20:08, minuitagency ***@***.***>:
