### ISSUE TITLE
Polygon appears 200km underneath the area I selected

### ISSUE THREAD

**Issue by minuitagency** [dev-event/react-native-maps-draw#6]
Hi, 

Thanks for the great library, 

When I draw my polygon, it doesn't appear at the same location when I release the draw, for example: 

![image](https://user-images.githubusercontent.com/38316888/143289103-804c2a76-a81e-4b41-ac3c-25d877b908b5.png)
![image](https://user-images.githubusercontent.com/38316888/143289115-b1e1da57-4dcd-45af-a7b8-326e1213944f.png)

`export default ({route}) => {
  const navigation = useNavigation();

  const mapRef = useRef(null);

  const initialPolygon = useRef({
    polygons: [],
    distance: 0,
    lastLatLng: undefined,
    initialLatLng: undefined,
    centerLatLng: undefined,
  });

  const [modePolygon, setPolygonCreated] = useState(false);

  const [isActiveDraw, setDrawMode] = useState(false);
  const [isReady, setIsReady] = useState(false);

  const [points, setPoints] = useState([]);

  const [polygon, setPolygon] = useState(initialPolygon.current);

  const handleMapReady = useCallback(
    () => mapRef.current && setIsReady(true),
    [],
  );

  const handleRemovePolygon = useCallback(() => {
    setPolygon(initialPolygon.current);
    setPolygonCreated(false);
  }, []);

  const handleClear = useCallback(() => {
    setPolygon(initialPolygon.current);
    setPolygonCreated(false);
    setPoints([]);
  }, []);

  const handleCanvasEndDraw = useCallback((locations) => {
    zoomCenterPolygon(locations.centerLatLng).then(() => {
      setPolygon(locations);
      setPolygonCreated(true);
    });

    setDrawMode((prevMode) => !prevMode);
  }, []);

  const zoomCenterPolygon = async (center) => {
    if (!mapRef.current) {
      return;
    }
    await mapRef.current.getCamera();
    if (Platform.OS === 'ios') {
      mapRef.current.animateCamera({
        center: center,
      });
    }
    if (Platform.OS === 'android') {
    }
  };

  const onPressToContinue = () => {
    try {
    } catch (e) {
      Alert.alert(e.message);
    }
  };

  const hasMarkerClose = polygon.centerLatLng && (
    <Marker
      onPress={handleRemovePolygon}
      coordinate={polygon.centerLatLng}></Marker>
  );

  const handlePolygon = useCallback(
    (item, index) => <Polygon key={index} coordinates={polygon.polygons} />,
    [polygon.polygons],
  );

  return (
    <View style={styles.container}>
      <SafeAreaView>
        <Header title={'Définissez la zone de votre manifestation'} />
        <Text style={[styles.descriptionText]}>
          {'Dessinez à la main les coutours de la zone de manifestation'}
        </Text>
      </SafeAreaView>

      <MapView
        showsUserLocation
        ref={mapRef}
        style={{flex: 1}}
        points={points}
        widthLine={3}
        onEndDraw={handleCanvasEndDraw}
        isDrawMode={isActiveDraw}
        onMapReady={handleMapReady}
        onStartDraw={handleClear}
        createdPolygon={modePolygon}
        onChangePoints={setPoints}
        backgroundCanvas={'rgba(0, 0, 0, 0.0)'}>
        {isReady &&
          modePolygon &&
          polygon.polygons &&
          polygon.polygons.length > 0 && (
            <>
              {hasMarkerClose}
              {polygon.polygons.map(handlePolygon)}
            </>
          )}
      </MapView>

      {points.length > 0 && (
        <BottomButton
          style={styles.toContinueButton}
          title={'Continuer'}
          onPress={onPressToContinue}
        />
      )}
    </View>
  );
};
`

Thanks, 

Théo

**Comment by dev-event** [comment]
Good afternoon. This project was thought of as an example. I made it
because a lot of people needed it. Please create issues git

[image: image.png]


ср, 24 нояб. 2021 г. в 20:46, minuitagency ***@***.***>:

**Comment by TheHuns** [comment]
@minuitagency are you using the most recent version of this package? I had a similar issues that was fixed in a patch not too long ago.

**Comment by minuitagency** [comment]
yes, I fixed it, it was an issue on my side with safe area view, I'm grappling with the issue "can't register two view AirMap" right now

**Comment by dev-event** [comment]
thanks

ср, 1 дек. 2021 г. в 16:47, minuitagency ***@***.***>:

**Comment by SharfMohiuddin** [comment]
I'm also facing this issue ""can't register two view AirMap" right now". Is there any resolution for it?
