### ISSUE TITLE
Error in Typescript project

### ISSUE THREAD

**Issue by SonalBacancy** [dev-event/react-native-maps-draw#8]
Module '"@dev-event/react-native-maps-draw"' has no exported member 'Polygon'. Did you mean to use 'import Polygon from "@dev-event/react-native-maps-draw"' instead? ts

```
import MapView, {
  LatLng,
  MapEvent,
  Polygon,
  PROVIDER_GOOGLE,
  MAP_TYPES,
  Camera,
  Region,
  Marker,
} from '@dev-event/react-native-maps-draw';
```

**Comment by dev-event** [comment]
Good afternoon. This project was thought of as an example. I made it
because a lot of people needed it. Please create issues git

[image: image.png]


пт, 26 нояб. 2021 г. в 13:17, SonalBacancy ***@***.***>:
